"""add_logistics_acceptance_note

Revision ID: 64e614c40475
Revises: 7807440a3009
Create Date: 2026-06-30 19:32:45.221389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e614c40475'
down_revision: Union[str, Sequence[str], None] = '7807440a3009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logistics', sa.Column('acceptance_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logistics', 'acceptance_note')
    # ### end Alembic commands ###
