"""create_logistics_table

Revision ID: 7807440a3009
Revises: 38112007949c
Create Date: 2026-06-30 19:17:44.991286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7807440a3009'
down_revision: Union[str, Sequence[str], None] = '38112007949c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('tracking', sa.String(length=255), nullable=False),
    sa.Column('ship_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invoice_file_key', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('in_transit', 'accepted', 'cancelled', name='logistics_status'), nullable=False),
    sa.Column('received_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expense_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logistics')
    # ### end Alembic commands ###
