"""initial empty schema

Revision ID: 8e2f6524fdf6
Revises: 
Create Date: 2026-06-29 20:11:07.040052

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '8e2f6524fdf6'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
